### ISSUE TITLE
nao_sensor_msgsConfig fails build

### ISSUE THREAD

**Issue by antbono** [ros-sports/nao_lola#44]
Ubuntu 22.04, ROS2 Rolling

When building the package i got the following error

![image](https://github.com/ros-sports/nao_lola/assets/7023471/36b98507-8dce-480b-882b-dc5a5d1eab3b)

Do you have the same issue?

**Comment by ijnek** [comment]
I cannot reproduce this issue. The error is saying it can't find nao_sensor_msgs installed, which is a binary dependency. Did you ensure you have dependencies installed correctly?

In your workspace:
`rosdep install --from-paths src -i`

**Comment by antbono** [comment]
Thanks for the reply. I missed this command in my setup.
